export type AllItemTypes = {
  id: number,
  createdAt: Date,
  updatedAt: Date,
  title: string | null,
  image1: string | null,
  image2: string | null,
  image3: string | null,
  image4: string | null,
  image5: string | null,
  description1: string | null,
  description2: string | null,
  description3: string | null,
  description4: string | null,
  description5: string | null,
  likeCount: number,
  lat: number | null,
  lon: number | null,
  location: string | null,
  googlePlace: string | null,
  published: boolean,
  category: string | null,
  authorId: number,
  author: {
    id: number,
    name: string | null,
    userIcon: string | null
  },
  viewCount?: number
}
